{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-sql-agent.fullname" . }}
  labels:
    {{- include "ai-sql-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  groq-api-key: {{ .Values.secret.groqApiKey | default .Values.app.groqApiKey | quote }}
  api-keys: {{ .Values.secret.apiKeys | default .Values.app.apiKeys | quote }}
  langfuse-public-key: {{ .Values.secret.langfusePublicKey | quote }}
  langfuse-secret-key: {{ .Values.secret.langfuseSecretKey | quote }}
{{- end -}}
